### ISSUE TITLE
Add support for svn:externals

### ISSUE THREAD

**Issue by Programie** [mikey179/releaseIt#8]
I have a project which has references to external SVN repositories. In my case I refer to the trunk of the external repository.

Currently if I want to release the project, ReleaseIt shows me the following error:

```
Can't create release, working directory not clean.
```

ReleaseIt should support repositories with external references and should automatically freeze the current revision of all externals and create the tag. TortoiseSVN supports that when creating tags.

**Comment by mikey179** [comment]
Close, as support for SVN repositories was dropped with 4b8a80b.
