### ISSUE TITLE
Unexpected behavior if something in the SVN URL contains /trunk

### ISSUE THREAD

**Issue by Programie** [mikey179/releaseIt#9]
ReleaseIt might does something unexpected if the SVN URL contains /trunk before the actual trunk folder (e.g. https://svn.example.com/trunk-switcher/trunk).

With the example URL above the findTagsUrl method would return "https://svn.example.com/tags" instead of the expected "https://svn.example.com/trunk-switcher/tags" URL.

**Comment by mikey179** [comment]
Close, as support for SVN repositories was dropped with 4b8a80b.
